# Generated by Django 4.0.6 on 2022-07-14 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_user_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genres',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='user_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_isbn', models.IntegerField()),
                ('to_read', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_reading', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
