# Generated by Django 4.0.6 on 2022-07-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_user_genres_user_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_book',
            name='book_isbn',
            field=models.TextField(),
        ),
    ]
