# Generated by Django 4.0.6 on 2022-08-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_id',
        ),
    ]
